#!/bin/sh

case "$1" in
start)
    echo "starting aesdsocket"
    start-stop-daemon --start --name aesdsocket --startas /usr/bin/aesdsocket
    ;;
stop)
    echo "stopping aesdsocket"
    start-stop-daemon --stop --name aesdsocket --signal SIGTERM
    ;;
*)
    echo "Usage: $0 start|stop"
    exit 1
    ;;
esac

exit 0
